import type { DepositRecord } from './shared'

export const initialDepositRecords: DepositRecord[] = [
  {
    id: 'STR-1028',
    member: 'Ibu Sari Wulandari',
    commodity: 'Kopi Robusta',
    weightKg: 420,
    submittedAt: '10 Jul 2026',
    qualityScore: 92,
    status: 'Dialokasi',
    collector: 'Raka',
    phone: '0812-4400-1028',
    origin: 'Dusun Cibuntu',
    notes: 'Sudah dialokasikan ke AGR-2026-014 untuk pemenuhan kopi robusta.',
  },
  {
    id: 'STR-1027',
    member: 'Pak Jaya Santoso',
    commodity: 'Kakao Fermentasi',
    weightKg: 315,
    submittedAt: '10 Jul 2026',
    qualityScore: 88,
    status: 'Lolos QC',
    collector: 'Mira',
    phone: '0812-4400-1027',
    origin: 'Dusun Pasir Jati',
    notes: 'Fermentasi merata dan siap direkomendasikan ke pool kakao.',
  },
  {
    id: 'STR-1026',
    member: 'Ibu Lilis Kurnia',
    commodity: 'Beras Organik',
    weightKg: 760,
    submittedAt: '09 Jul 2026',
    qualityScore: null,
    status: 'Menunggu QC',
    collector: 'Raka',
    phone: '0812-4400-1026',
    origin: 'Dusun Sukamaju',
    notes: 'Menunggu pengukuran kadar air sebelum masuk stok siap alokasi.',
  },
  {
    id: 'STR-1025',
    member: 'Pak Maman Suparman',
    commodity: 'Kopi Robusta',
    weightKg: 505,
    submittedAt: '09 Jul 2026',
    qualityScore: 90,
    status: 'Lolos QC',
    collector: 'Dewi',
    phone: '0812-4400-1025',
    origin: 'Dusun Cikadu',
    notes: 'Ukuran biji seragam, prioritas untuk kontrak kopi minggu ini.',
  },
  {
    id: 'STR-1024',
    member: 'Ibu Ningsih',
    commodity: 'Kakao Fermentasi',
    weightKg: 280,
    submittedAt: '08 Jul 2026',
    qualityScore: null,
    status: 'Tercatat',
    collector: 'Mira',
    phone: '0812-4400-1024',
    origin: 'Dusun Cileuweung',
    notes: 'Setoran baru diterima dan belum masuk antrean pemeriksaan kualitas.',
  },
]
